### ISSUE TITLE
Decide on output file format

### ISSUE THREAD

**Issue by sgrieve** [sgrieve/GeoMeta#1]
We need a structured text format, so json or yaml would work.

Json has the advantage that we can build on [geojson](http://geojson.org).

**Comment by ageorgou** [comment]
I would suggest supporting both (perhaps JSON being default?) and having a command line option to choose. Converting between the two should be straightforward.

**Comment by sgrieve** [comment]
We are going to use JSON in the first instance and then look at yaml as a future feature.
