### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by sgrieve** [sgrieve/GeoMeta#15]
We need to write up a readme for the project. As a minimum it should contain:

- [x] Project overview
- [x] What problem it solves
- [x] Contribution guidelines
- [x] Install guide
- [x] Usage examples

From the talk today, our readme should cover:

```
§ Value of work should be clear – or lose marks!
§ Context - building on existing work, starting something new?
§ What does your software/scripts do?
§ How does it benefit others, and who?
§ What’s novel about your work?
§ Future potential – interesting ideas for future steps
```

**Comment by r-j-arnold** [comment]
Stuart probably best to do this as the most aware of the academic context

**Comment by sgrieve** [comment]
working on it now!

**Comment by sgrieve** [comment]
Readme finished!
