### ISSUE TITLE
Decide on the metadata we need to store

### ISSUE THREAD

**Issue by sgrieve** [sgrieve/GeoMeta#2]
We will need as a minimum:

- bounding box
- spatial reference system
- doi of source data
- doi of paper?
- others?

**Comment by ageorgou** [comment]
To implement the round-trip transformation as per #9, we will need to write a new file using `rasterio`, which in turn requires the following fields (http://rasterio.readthedocs.io/en/latest/quickstart.html#opening-a-dataset-in-writing-mode):

* driver
* width
* height
* count
* dtype

The following are listed as optional, so they probably should be recorded to make sure the transformation is correct:
* crs
* transform
* nodata

**Comment by ageorgou** [comment]
We are currently leaving the nodata field out (see the (code) comments in 1621e45 for details of why). 

Note that this shouldn't affect the process, since locations with missing data should be ignored anyway.
