### ISSUE TITLE
Look at charme

### ISSUE THREAD

**Issue by ageorgou** [sgrieve/GeoMeta#21]
Investigate charmed and pycharmed to see if there are any useful similarities or things we can draw on.

**Comment by sammiebuzzard** [comment]
http://www.charme.org.uk

CHARMe allows users to comment on metadata, it doesn't seem to explicitly create metadata in a way that would be useful to us.

It does have a nice visualisation tool and is something we could link with in the future so users could add their GeoMeta json file to the comments in addition to having it attached to publications.
